apiVersion: v2
name: pravega

type: application

version: 0.1.0

appVersion: "1.0"

dependencies:
  - name: pravega-operator
    version: 0.6.2
    repository: https://charts.pravega.io
  - name: pravega
    version: 0.10.4
    repository: https://charts.pravega.io
