apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pravega
helmCharts:
  - name: pravega-operator
    releaseName: pravega-operator
    version: 0.10.4
    repo: https://charts.pravega.io
