apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: trilium
  namespace: trilium
spec:
  replicas: 1
  serviceName: trilium-service
  selector:
    matchLabels:
      app: trilium
  template:
    metadata:
      labels:
        app: trilium
    spec:
      containers:
        - name: trilium
          image: zadam/trilium:0.59-latest
          resources:
            limits:
              cpu: 2
              memory: 2Gi
            requests:
              cpu: 1
              memory: 1Gi
          env:
            - name: TRILIUM_DB_FILE
              value: /data/trilium.sqlite
            - name: TRILIUM_DATA_DIR
              value: /data
            - name: TRILIUM_PORT
              value: "8080"
            - name: PORT
              value: "8080"
          ports:
            - name: trilium
              containerPort: 8080
              protocol: TCP
          volumeMounts:
            - name: trilium-data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: trilium-data
      spec:
        accessModes: ["ReadWriteOnce"]
        volumeMode: Filesystem
        resources:
          requests:
            storage: 1Gi