kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  namespace: pravega
  name: pravega-tier2
spec:
  storageClassName: "nfs"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
